version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.7
  - dependency-name: elliptic
    versions:
    - 6.5.3
  commit-message:
    prefix: build
    prefix-development: chore
